import Head from "next/head";
import { Inter } from "next/font/google";
import NavBar from "@/components/header/NavBar";
import ProductBanner from "@/components/header/ProductBanner";
import ProductSection from "@/components/sections/ProductSection";
import FooterSubscription from "@/components/footer/FooterSubscription";
import FooterNavigation from "@/components/footer/FooterNavigation";;

const inter = Inter({ subsets: ["latin"] });
export const getStaticProps = async (context) => {
  const productData = await (
    await fetch(`https://fakestoreapi.com/products`)
  ).json();
  return {
    props: {
      productData,
    },
  };
};

export default function Home({ productData }) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar />
        <ProductBanner />
        <ProductSection productData={productData} />
      </main>
      <footer className="footer">
        <FooterSubscription />
        <FooterNavigation />
      </footer>
    </>
  );
}
